cmake_minimum_required(VERSION 3.22.1)
project(hr54_whisper LANGUAGES C CXX)
set(CMAKE_CXX_STANDARD 17)
set(BUILD_SHARED_LIBS OFF CACHE BOOL "" FORCE)
set(WHISPER_BUILD_TESTS OFF CACHE BOOL "" FORCE)
set(WHISPER_BUILD_EXAMPLES OFF CACHE BOOL "" FORCE)
set(GGML_OPENMP OFF CACHE BOOL "" FORCE)
set(GGML_NATIVE OFF CACHE BOOL "" FORCE)
set(GGML_CPU_KLEIDIAI OFF CACHE BOOL "" FORCE)
add_subdirectory(whisper)
add_library(hr54-whisper SHARED whisper_jni.cpp)
target_link_libraries(hr54-whisper PRIVATE whisper android log)
target_compile_options(hr54-whisper PRIVATE -O3)
target_link_options(hr54-whisper PRIVATE "-Wl,-z,max-page-size=16384")
