#include "modules.h"
#include "internal.h"
int api_module_id(const char *id){size_t n=id?strlen(id):0;if(!n||n>=64||!strchr("abcdefghijklmnopqrstuvwxyz0123456789",id[0]))return 0;for(size_t i=1;i<n;i++)if(!strchr("abcdefghijklmnopqrstuvwxyz0123456789._-",id[i]))return 0;return 1;}
static int route(char *path,size_t size,const char *id,const char *operation){if(!api_module_id(id))return -1;int n=snprintf(path,size,"/api/modules/%s/%s",id,operation);return n<0||(size_t)n>=size?-1:0;}
int api_modules(ApiClient *a){return get(a,API_BROWSE,API_MODULES,"/api/modules",6000);}
int api_module_browse(ApiClient *a,const char *id,const char *parent,const char *query,int offset){
    char p[800],q[800],path[1800],base[128];if(offset<0||api_encode(p,sizeof p,parent)||api_encode(q,sizeof q,query)||route(base,sizeof base,id,*query?"search":"browse"))return -1;
    int n=snprintf(path,sizeof path,"%s?parent=%s&q=%s&offset=%d&limit=%d",base,p,q,offset,UI_PAGE_SIZE);if(n<0||(size_t)n>=sizeof path)return -1;
    return get(a,API_BROWSE,API_MEDIA,path,120000);
}
int api_module_play(ApiClient *a,const char *id,const MediaItem *item){char path[128],quoted[600],body[720];if(route(path,sizeof path,id,"play")||json_quote(quoted,sizeof quoted,item->id))return -1;snprintf(body,sizeof body,"{\"itemId\":%s,\"startSeconds\":%ld}",quoted,item->resume);return post(a,API_OPERATION,API_PLAY,path,body,240000);}
int api_module_settings(ApiClient *a,const char *id){char path[128];return route(path,sizeof path,id,"settings")?-1:get(a,API_BROWSE,API_MODULE_SETTINGS,path,120000);}
int api_module_save(ApiClient *a,const char *id,const ModuleField *field){char path[128],key[140],value[600],body[800];if(route(path,sizeof path,id,"settings")||json_quote(key,sizeof key,field->key))return -1;if(field->quoted){if(json_quote(value,sizeof value,field->value))return -1;}else ui_copy(value,sizeof value,field->value);snprintf(body,sizeof body,"{%s:%s}",key,value);return post(a,API_OPERATION,API_MODULE_SAVE,path,body,120000)==0?0:-1;}
int api_module_action(ApiClient *a,const char *id,const char *action){char path[200],operation[96];if(!api_module_id(action))return -1;snprintf(operation,sizeof operation,"actions/%s",action);return route(path,sizeof path,id,operation)?-1:post(a,API_BROWSE,API_MODULE_ACTION,path,"{}",120000);}
int api_module_manage(ApiClient *a,const char *id,const char *action){char path[128];if(strcmp(action,"enable")&&strcmp(action,"disable")&&strcmp(action,"reinstall")&&strcmp(action,"uninstall"))return -1;if(route(path,sizeof path,id,action))return -1;if(!strcmp(action,"uninstall")){snprintf(path,sizeof path,"/api/modules/%s",id);return api_send(a,API_OPERATION,API_MODULE_MUTATE,"DELETE",path,"{}",180000);}return post(a,API_OPERATION,API_MODULE_MUTATE,path,"{}",180000);}
int api_module_install(ApiClient *a,const char *url){char value[2200],body[2300];if(strlen(url)>1024||json_quote(value,sizeof value,url))return -1;snprintf(body,sizeof body,"{\"url\":%s}",value);return post(a,API_OPERATION,API_MODULE_MUTATE,"/api/modules/install",body,240000);}
int api_management_pair_open(ApiClient *a){return post(a,API_BROWSE,API_MANAGEMENT_PAIR,"/api/management/pair/open","{}",6000);}
int api_module_native(ApiClient *a,const char *id,const char *operation){char path[160],action[48];int status=!strcmp(operation,"status"),start=!strcmp(operation,"start");if(!status&&!start&&strcmp(operation,"stop"))return -1;snprintf(action,sizeof action,"native/%s",operation);if(route(path,sizeof path,id,action))return -1;return status?get(a,API_STATUS,API_NATIVE_STATUS,path,6000):post(a,start?API_OPERATION:API_CONTROL,start?API_NATIVE_START:API_NATIVE_STOP,path,"{}",60000);}
int api_module_image(ApiClient *a,const char *id,const char *art){char path[1000],escaped[800],operation[840];if(!art||!*art)ui_copy(operation,sizeof operation,"icon");else{if(api_encode(escaped,sizeof escaped,art))return -1;snprintf(operation,sizeof operation,"art/%s",escaped);}return route(path,sizeof path,id,operation)?-1:get(a,API_ARTWORK,API_IMAGE,path,20000);}
