#include "state.h"
#include "../ui/animation.h"
static const char *source_name[]={"Jellyfin","IPTV","Frigate","YouTube","Doom"};
BrowseNode *app_node(App *a){return a->source<SOURCE_DOOM?&a->sources[a->source].node[a->sources[a->source].depth]:NULL;}
const MediaItem *app_selected(App *a){BrowseNode *n=app_node(a);return n&&n->selection>=0&&n->selection<n->list.count?&n->list.item[n->selection]:NULL;}
static void screen(App *a,Screen s){if(a->screen!=s){fprintf(stderr,"presentation-trace: screen=%d->%d playing=%d generation=%u\n",a->screen,s,a->playback.playing,a->playback.generation);a->previous=a->screen;a->screen=s;}a->visible=s!=SCREEN_HIDDEN&&s!=SCREEN_DOOM;a->dirty=1;}
void app_init(App *a,int port){memset(a,0,sizeof(*a));api_init(&a->api,port);a->screen=SCREEN_STARTUP;a->return_screen=SCREEN_HOME;a->visible=1;a->dirty=1;a->bitrate=12000000;for(int i=0;i<4;i++){a->sources[i].node[0].kind=BROWSE_ROOT;ui_copy(a->sources[i].node[0].title,256,source_name[i]);}ui_copy(a->message,sizeof(a->message),"Starting display");}
static void playback_return(App *a){
    /* Existing playback may predate this frontend process. Only saved browse
       destinations are meaningful; startup/presentation states are transient. */
    Screen target=a->return_screen;
    if(target!=SCREEN_HOME&&target!=SCREEN_BROWSER&&target!=SCREEN_DETAILS)target=SCREEN_HOME;
    a->source=a->return_source;a->frontend_prepared=0;a->prepare_due=0;screen(a,target);
}
void app_free(App *a){api_close(&a->api);artwork_free(&a->artwork);}
void app_error(App *a,ApiError e){a->loading=0;a->error_return=a->screen;ui_copy(a->message,sizeof(a->message),api_error_message(e));screen(a,SCREEN_ERROR);}
static void notice(App *a,const char *text){ui_copy(a->notice,sizeof(a->notice),text);a->notice_until=ui_now()+3500;a->dirty=1;}
static void invalidate(App *a){++a->api.generation;api_cancel(&a->api,API_BROWSE);api_cancel(&a->api,API_ARTWORK);a->artwork.pending[0]=0;a->loading=0;}
void app_load(App *a){BrowseNode *n=app_node(a);if(!n)return;int rc=-1;invalidate(a);a->loading=1;screen(a,SCREEN_BROWSER);
    switch(a->source){case SOURCE_JELLYFIN:rc=n->kind==BROWSE_ROOT?api_jellyfin_libraries(&a->api):api_jellyfin_items(&a->api,n->parent,n->query,n->offset,n->kind==BROWSE_RESUME);break;case SOURCE_IPTV:rc=n->kind==BROWSE_ROOT?api_iptv_groups(&a->api,n->offset):api_iptv_channels(&a->api,n->parent,n->query,n->offset,n->kind==BROWSE_CHANNELS);break;case SOURCE_FRIGATE:rc=api_frigate_cameras(&a->api);break;case SOURCE_YOUTUBE:rc=api_youtube_search(&a->api,n->query,n->offset);break;default:break;}
    if(rc)app_error(a,API_FAILED);
}
static void open_source(App *a){a->source=(Source)a->home;if(a->source==SOURCE_DOOM){if(api_busy(&a->api,API_OPERATION)){notice(a,"Please wait for the current operation.");return;}invalidate(a);a->doom_starting=1;a->return_screen=SCREEN_HOME;screen(a,SCREEN_DOOM);return;}
    BrowseNode *n=app_node(a);if(a->source==SOURCE_JELLYFIN&&!a->authenticated){invalidate(a);a->loading=1;screen(a,SCREEN_PAIR);if(api_auth_status(&a->api))app_error(a,API_FAILED);return;}
    if(a->source==SOURCE_YOUTUBE&&!n->loaded){a->return_screen=SCREEN_BROWSER;a->keyboard_focus=0;a->query[0]=0;screen(a,SCREEN_KEYBOARD);return;}
    if(n->loaded)screen(a,SCREEN_BROWSER);else app_load(a);
}
static void push_node(App *a,BrowseKind kind,const char *parent,const char *title,const char *query){SourceState *s=&a->sources[a->source];if(s->depth+1>=NAV_DEPTH){notice(a,"This folder is too deep to open.");return;}BrowseNode *n=&s->node[++s->depth];memset(n,0,sizeof(*n));n->kind=kind;ui_copy(n->parent,sizeof(n->parent),parent);ui_copy(n->title,sizeof(n->title),title);ui_copy(n->query,sizeof(n->query),query);app_load(a);}
static void back_browser(App *a){SourceState *s=&a->sources[a->source];invalidate(a);if(s->depth){s->depth--;screen(a,SCREEN_BROWSER);}else screen(a,SCREEN_HOME);}
static void play(App *a){const MediaItem *item=app_selected(a);if(!item||!item->playable){notice(a,"This item is not available for playback.");return;}if(api_busy(&a->api,API_OPERATION)){notice(a,"Please wait for the current operation.");return;}a->return_screen=a->screen;a->return_source=a->source;a->operation_source=a->source;a->loading=1;a->cancel_play=0;a->awaiting=API_PLAY;screen(a,SCREEN_PLAYER);ui_copy(a->playback.title,sizeof(a->playback.title),item->title);if(api_playback_start(&a->api,a->source,item))app_error(a,API_FAILED);}
static void keyboard(App *a){if(a->source==SOURCE_YOUTUBE&&a->playback.playing){notice(a,"Stop playback before searching YouTube.");return;}a->return_screen=a->screen;a->keyboard_focus=0;BrowseNode *n=app_node(a);ui_copy(a->query,sizeof(a->query),n?n->query:"");screen(a,SCREEN_KEYBOARD);}
static void finish_search(App *a){if(!a->query[0]){notice(a,"Enter something to search for.");return;}if(a->source==SOURCE_YOUTUBE){BrowseNode *n=app_node(a);n->kind=BROWSE_RESULTS;n->offset=0;n->selection=0;ui_copy(n->query,sizeof(n->query),a->query);ui_copy(n->title,sizeof(n->title),"Search results");app_load(a);}else push_node(a,BROWSE_ITEMS,"","Search results",a->query);}
static void delete_query(App *a){size_t n=strlen(a->query);if(n){do{--n;}while(n&&((unsigned char)a->query[n]&192)==128);a->query[n]=0;}}
void app_key(void *ctx,KeyEvent ev){App *a=ctx;if(!ev.pressed)return;
    /* The physical DIRECTV remote uses LEFT for Back, with no distinct BACK
     * button. Keep genuine horizontal navigation, but allow backing out of
     * list/detail/player/pair/error screens and non-adjustable settings rows.
     * Normalize before repeat filtering so a held LEFT does not pop folders. */
    if(ev.key==KEY_LEFT&&(a->screen==SCREEN_BROWSER||a->screen==SCREEN_DETAILS||a->screen==SCREEN_PLAYER||a->screen==SCREEN_PAIR||a->screen==SCREEN_ERROR||(a->screen==SCREEN_SETTINGS&&a->settings_focus!=0))){fprintf(stderr,"controller-action: LEFT as BACK screen=%d\n",a->screen);ev.key=KEY_BACK;}
    fprintf(stderr,"hr54-ui: key=%d screen=%d repeat=%d\n",ev.key,a->screen,ev.repeat);uint64_t now=ui_now();int direction=ev.key==KEY_UP||ev.key==KEY_DOWN||ev.key==KEY_LEFT||ev.key==KEY_RIGHT;
    if(ev.repeat&&(!direction||now-a->last_key<90))return;a->last_key=now;a->dirty=1;
    if(ev.key==KEY_GUIDE||ev.key==KEY_MENU){a->revealed_play_generation=a->playback.generation;a->frontend_prepared=0;a->prepare_due=0;invalidate(a);if(a->doom_running||a->doom_starting||a->api.r[API_OPERATION].kind==API_DOOM_START){a->doom_returning=1;if(a->doom_starting){a->doom_starting=0;a->doom_returning=0;screen(a,SCREEN_HOME);}else if(a->doom_running&&api_doom_stop(&a->api))notice(a,"Waiting for Doom to close.");}else screen(a,SCREEN_HOME);return;}
    if(ev.key==KEY_EXIT){screen(a,a->playback.playing?SCREEN_HIDDEN:SCREEN_HOME);api_tv_exit(&a->api);return;}
    if(ev.key==KEY_STOP){if(a->doom_running){a->doom_returning=1;api_doom_stop(&a->api);}else if(a->playback.playing||a->awaiting==API_PLAY){a->cancel_play=1;Source owner=a->playback.active_source>=0?(Source)a->playback.active_source:a->operation_source;api_playback_stop(&a->api,owner);}return;}
    if(ev.key==KEY_PLAY&&a->playback.playing){if(a->playback.paused&&a->playback.can_resume){a->loading=1;api_playback_pause(&a->api,1);a->player_until=now+5000;screen(a,SCREEN_PLAYER);}else if(a->playback.paused)notice(a,"Resume is not available for this source.");return;}
    /* The RF remote's combined PLAY/PAUSE sends e401 for both presses. */
    if(ev.key==KEY_PAUSE&&a->playback.playing){int resume=a->playback.paused;if(resume?a->playback.can_resume:a->playback.can_pause){if(api_busy(&a->api,API_CONTROL)){notice(a,"Please wait for the current operation.");return;}if(api_playback_pause(&a->api,resume)){notice(a,"Playback control is unavailable.");return;}a->loading=1;a->player_until=now+5000;screen(a,SCREEN_PLAYER);}else notice(a,resume?"Resume is not available for this source.":"Pause is not available for this source.");return;}
    if((ev.key==KEY_FORWARD||ev.key==KEY_REWIND)&&a->playback.playing){if(a->playback.can_seek){a->loading=1;api_playback_seek(&a->api,ev.key==KEY_FORWARD?30:-30);screen(a,SCREEN_PLAYER);}else notice(a,"Seeking is not available for this source.");return;}
    if((ev.key==KEY_SKIP_FORWARD||ev.key==KEY_SKIP_BACK)&&a->playback.playing){if(a->playback.can_seek){a->loading=1;api_playback_seek(&a->api,ev.key==KEY_SKIP_FORWARD?30:-10);a->player_until=now+5000;screen(a,SCREEN_PLAYER);}else notice(a,"Skipping is not available for this source.");return;}
    if(ev.key==KEY_INFO&&a->playback.playing){a->player_until=now+5000;screen(a,SCREEN_PLAYER);return;}
    if(a->screen==SCREEN_STARTUP){return;}
    if(a->screen==SCREEN_HOME){if(ev.key==KEY_LEFT||ev.key==KEY_RIGHT){int delta=ev.key==KEY_RIGHT?1:-1;a->home_motion=a->home_motion*(1000-ui_transition_progress(a->animate_start,now))/1000+delta*1000;a->home_from=a->home;a->home=(a->home+delta+5)%5;a->home_direction=delta;a->animate_start=now;}else if(ev.key==KEY_DOWN||ev.key==KEY_UP){screen(a,SCREEN_SETTINGS);a->loading=1;if(api_settings_get(&a->api))app_error(a,API_FAILED);}else if(ev.key==KEY_SELECT)open_source(a);else if(ev.key==KEY_BACK){screen(a,a->playback.playing?SCREEN_HIDDEN:SCREEN_HOME);api_tv_exit(&a->api);}return;}
    if(a->screen==SCREEN_HIDDEN){if(ev.key==KEY_INFO)screen(a,SCREEN_PLAYER);return;}
    if(a->screen==SCREEN_ERROR){if(ev.key==KEY_BACK){screen(a,a->error_return==SCREEN_STARTUP?SCREEN_HOME:a->error_return);a->loading=0;}else if(ev.key==KEY_SELECT){if(a->error_return==SCREEN_BROWSER)app_load(a);else if(a->error_return==SCREEN_SETTINGS){screen(a,SCREEN_SETTINGS);a->loading=1;api_settings_get(&a->api);}else if(a->error_return==SCREEN_PAIR){screen(a,SCREEN_PAIR);api_auth_status(&a->api);}else if(a->error_return==SCREEN_STARTUP){screen(a,SCREEN_STARTUP);a->next_status=0;}else screen(a,SCREEN_HOME);}return;}
    if(a->screen==SCREEN_PAIR){if(ev.key==KEY_BACK){invalidate(a);screen(a,SCREEN_HOME);}else if(ev.key==KEY_SELECT&&!a->loading){a->loading=1;if(api_auth_pair(&a->api))app_error(a,API_FAILED);}return;}
    if(a->screen==SCREEN_KEYBOARD){int focus=a->keyboard_focus;if(direction){int delta=ev.key==KEY_LEFT?-1:ev.key==KEY_RIGHT?1:ev.key==KEY_UP?-10:10;a->keyboard_focus=(focus+delta+50)%50;}else if(ev.key==KEY_BACK){if(*a->query)delete_query(a);else screen(a,a->return_screen);}else if(ev.key==KEY_SELECT){const char *letters=a->keyboard_upper?"ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789-.'?":"abcdefghijklmnopqrstuvwxyz0123456789-.'?";if(focus<40){size_t n=strlen(a->query);if(n<64&&letters[focus]){a->query[n]=letters[focus];a->query[n+1]=0;}}else if(focus==40)a->keyboard_upper=!a->keyboard_upper;else if(focus==41){size_t n=strlen(a->query);if(n<64){a->query[n]=' ';a->query[n+1]=0;}}else if(focus==42)delete_query(a);else if(focus==43)a->query[0]=0;else if(focus>=44&&focus<=47)finish_search(a);else screen(a,a->return_screen);}return;}
    if(a->screen==SCREEN_SETTINGS){if(ev.key==KEY_BACK){invalidate(a);screen(a,SCREEN_HOME);}else if(ev.key==KEY_UP||ev.key==KEY_DOWN)a->settings_focus=(a->settings_focus+(ev.key==KEY_DOWN?1:3))%4;else if(ev.key==KEY_LEFT||ev.key==KEY_RIGHT){if(a->settings_focus==0){if(a->quality_count){int i=0;for(int q=0;q<a->quality_count;q++)if(a->quality_rates[q]==a->bitrate)i=q;a->bitrate=a->quality_rates[(i+(ev.key==KEY_RIGHT?1:a->quality_count-1))%a->quality_count];}}}else if(ev.key==KEY_SELECT){if(a->settings_focus==0){a->loading=1;if(api_settings_save(&a->api,a->bitrate))app_error(a,API_FAILED);}else if(a->settings_focus==1){a->source=SOURCE_JELLYFIN;screen(a,SCREEN_PAIR);api_auth_status(&a->api);}else if(a->settings_focus==2){a->loading=1;if(api_auth_logout(&a->api))app_error(a,API_FAILED);}else screen(a,SCREEN_HOME);}return;}
    if(a->screen==SCREEN_PLAYER){if(ev.key==KEY_BACK){if(a->loading&&a->awaiting==API_PLAY){a->cancel_play=1;api_playback_stop(&a->api,a->operation_source);screen(a,a->return_screen);}else screen(a,SCREEN_HIDDEN);}else if(ev.key==KEY_SELECT&&a->playback.playing&&a->playback.can_stop){a->loading=1;api_playback_stop(&a->api,a->operation_source);}return;}
    if(a->screen==SCREEN_DETAILS){if(ev.key==KEY_BACK)screen(a,SCREEN_BROWSER);else if(ev.key==KEY_SELECT)play(a);return;}
    if(a->screen==SCREEN_BROWSER){BrowseNode *n=app_node(a);if(ev.key==KEY_BACK){back_browser(a);return;}if(a->loading)return;if(ev.key==KEY_INFO){if(a->source==SOURCE_JELLYFIN||a->source==SOURCE_IPTV||a->source==SOURCE_YOUTUBE)keyboard(a);return;}if(ev.key==KEY_UP||ev.key==KEY_DOWN){int next=n->selection+(ev.key==KEY_DOWN?1:-1);if(next>=n->list.count&&n->list.has_more){n->offset+=a->source==SOURCE_YOUTUBE?1:n->list.count-(a->source==SOURCE_IPTV&&n->kind==BROWSE_ROOT&&!n->offset?1:0);n->selection=0;app_load(a);}else if(next<0&&n->offset>0){n->offset-=a->source==SOURCE_YOUTUBE?1:UI_PAGE_SIZE;if(n->offset<0)n->offset=0;n->selection=0;app_load(a);}else if(next>=0&&next<n->list.count){n->selection=next;a->art_due=now+120;}return;}if(ev.key==KEY_RIGHT){if(a->source!=SOURCE_FRIGATE)keyboard(a);return;}if(ev.key==KEY_SELECT){const MediaItem *x=app_selected(a);if(!x)return;if(x->folder){char id[256],title[256];ui_copy(id,sizeof(id),x->id);ui_copy(title,sizeof(title),x->title);push_node(a,a->source==SOURCE_IPTV?(x->virtual_entry?BROWSE_ITEMS:BROWSE_CHANNELS):!strcmp(x->id,"@resume")?BROWSE_RESUME:BROWSE_ITEMS,x->virtual_entry?"":id,title,"");}else if(a->source==SOURCE_JELLYFIN)screen(a,SCREEN_DETAILS);else play(a);}return;}
}
void app_response(void *ctx,const ApiResponse *r){App *a=ctx;if(r->kind==API_IMAGE){if(r->generation==a->api.generation){if(artwork_queue(&a->artwork,r->bytes,r->length,r->error==API_OK,r->generation)){artwork_accept(&a->artwork,NULL,0,0);a->dirty=1;}}return;}
    int browse=r->kind==API_POLL||r->kind==API_AUTH||r->kind==API_LIBRARIES||r->kind==API_ITEMS||r->kind==API_RESUME||r->kind==API_GROUPS||r->kind==API_CHANNELS||r->kind==API_CAMERAS||r->kind==API_SEARCH||r->kind==API_SETTINGS;
    if(browse&&r->generation!=a->api.generation)return;
    ApiModel *m=calloc(1,sizeof(*m));if(!m){app_error(a,API_FAILED);return;}ApiError e=r->error;if(e==API_OK&&api_model(r,m))e=API_MALFORMED;
    if(e!=API_OK){fprintf(stderr,"hr54-ui: API kind=%d status=%d error=%d\n",r->kind,r->status,e);if(r->kind==API_STATE){/* Background telemetry must never flash an operation-error banner.  Back off while preserving the last coherent state; every poll uses a fresh socket. */if(a->status_failures<6)a->status_failures++;a->next_status=ui_now()+(uint64_t)(1<<a->status_failures)*1000;}else if(r->kind==API_DOOM_STATUS||r->kind==API_EXIT){notice(a,api_error_message(e));}else if(r->kind==API_PREPARE){a->frontend_prepared=0;a->prepare_due=UINT64_MAX;notice(a,"Preparing remote control. Press MENU to retry.");}else if(r->kind==API_READY){a->next_status=ui_now()+2000;ui_copy(a->message,sizeof(a->message),"Waiting for the receiver service");a->dirty=1;}else{if(r->kind==API_DOOM_START||r->kind==API_DOOM_STOP){a->doom_starting=0;a->doom_running=1;a->doom_returning=r->kind==API_DOOM_START;a->next_status=0;screen(a,SCREEN_DOOM);notice(a,api_error_message(e));}else app_error(a,e);}free(m);return;}
    if(r->kind!=API_STATE&&r->kind!=API_DOOM_STATUS)a->dirty=1;switch(r->kind){case API_READY:a->ready=m->ready;ui_copy(a->message,sizeof(a->message),"Connecting remote control");if(m->running){a->doom_running=1;a->home=4;screen(a,SCREEN_DOOM);}else{screen(a,a->start_hidden?SCREEN_HIDDEN:SCREEN_HOME);a->start_hidden=0;}break;
    case API_PREPARE:a->frontend_prepared=m->prepared;break;
    case API_AUTH:a->authenticated=m->authenticated;a->loading=0;if(m->authenticated){a->awaiting=API_LIBRARIES;}else{ui_copy(a->pair_code,sizeof(a->pair_code),m->code);screen(a,SCREEN_PAIR);}break;
    case API_PAIR:a->loading=0;ui_copy(a->pair_code,sizeof(a->pair_code),m->code);a->next_status=ui_now()+2000;if(a->screen==SCREEN_PAIR)a->dirty=1;break;
    case API_POLL:a->authenticated=m->authenticated;if(m->authenticated){a->pair_code[0]=0;a->awaiting=API_LIBRARIES;}else if(!m->pending){a->pair_code[0]=0;notice(a,"That code expired. Select to get a new code.");}break;
    case API_LIBRARIES:case API_ITEMS:case API_RESUME:case API_GROUPS:case API_CHANNELS:case API_CAMERAS:case API_SEARCH:{BrowseNode *n=app_node(a);n->list=m->list;n->loaded=1;a->loading=0;if(r->kind==API_LIBRARIES){/* Coherent backend-backed native entry points, no upstream transforms. */int count=n->list.count;if(count<=UI_PAGE_SIZE-2){memmove(n->list.item+2,n->list.item,count*sizeof(MediaItem));MediaItem *all=&n->list.item[0],*resume=&n->list.item[1];memset(all,0,2*sizeof(*all));ui_copy(all->id,sizeof(all->id),"@all");ui_copy(all->title,sizeof(all->title),"All titles");all->folder=1;all->virtual_entry=1;ui_copy(resume->id,sizeof(resume->id),"@resume");ui_copy(resume->title,sizeof(resume->title),"Continue Watching");resume->folder=1;resume->virtual_entry=1;n->list.count+=2;n->list.total+=2;}}if(r->kind==API_GROUPS&&!n->offset&&n->list.count<UI_PAGE_SIZE){memmove(n->list.item+1,n->list.item,n->list.count*sizeof(MediaItem));MediaItem *all=&n->list.item[0];memset(all,0,sizeof(*all));ui_copy(all->id,sizeof(all->id),"@all");ui_copy(all->title,sizeof(all->title),"All channels");all->folder=1;all->virtual_entry=1;n->list.count++;n->list.total++;}if(n->selection>=n->list.count)n->selection=n->list.count?n->list.count-1:0;if(r->kind==API_ITEMS||r->kind==API_RESUME)n->list.has_more=n->offset+n->list.count<n->list.total;a->art_due=ui_now()+100;break;}
    case API_STATE:{a->status_failures=0;if(m->playback.generation<a->observed_play_generation)break;int ended=a->playback.playing&&!m->playback.playing;int committed=m->playback.playing&&m->playback.generation>a->observed_play_generation;if(committed){a->observed_play_generation=m->playback.generation;if(!a->awaiting){if(a->screen==SCREEN_HOME||a->screen==SCREEN_BROWSER||a->screen==SCREEN_DETAILS){a->return_screen=a->screen;a->return_source=a->source;}}if(a->revealed_play_generation!=m->playback.generation)screen(a,SCREEN_HIDDEN);}if(memcmp(&a->playback,&m->playback,sizeof(PlaybackState))){a->dirty=1;a->playback=m->playback;}if(ended&&(a->screen==SCREEN_HIDDEN||a->screen==SCREEN_PLAYER)&&a->awaiting!=API_PLAY){a->loading=0;a->player_until=0;playback_return(a);}break;}
    case API_PLAY:a->awaiting=0;a->loading=0;a->playback.playing=1;if(m->playback.generation){a->playback.generation=m->playback.generation;a->observed_play_generation=m->playback.generation;}if(a->cancel_play){a->stop_after_play=1;}else if(a->screen==SCREEN_PLAYER)screen(a,SCREEN_HIDDEN);a->next_status=0;break;
    case API_STOP:a->loading=0;if(a->awaiting!=API_PLAY){a->playback.playing=0;playback_return(a);}break;
    case API_PAUSE:case API_SEEK:a->loading=0;a->next_status=0;break;
    case API_SETTINGS:case API_SAVE_SETTINGS:a->loading=0;if(m->bitrate)a->bitrate=m->bitrate;a->quality_count=m->quality_count;memcpy(a->quality_rates,m->quality_rates,sizeof(a->quality_rates));if(r->kind==API_SAVE_SETTINGS)notice(a,"Playback quality saved.");break;
    case API_LOGOUT:invalidate(a);a->loading=0;a->authenticated=0;memset(&a->sources[SOURCE_JELLYFIN],0,sizeof(SourceState));ui_copy(a->sources[0].node[0].title,256,"Jellyfin");artwork_reset(&a->artwork);notice(a,"Jellyfin account disconnected.");break;
    case API_DOOM_START:a->doom_starting=0;a->doom_running=m->running;if(!a->doom_returning&&m->running)screen(a,SCREEN_DOOM);if(!m->running){screen(a,SCREEN_HOME);app_error(a,API_FAILED);}a->next_status=0;break;
    case API_DOOM_STATUS:if(a->doom_running&&!m->running){a->doom_running=0;a->doom_returning=0;screen(a,SCREEN_HOME);}break;
    case API_DOOM_STOP:if(m->running){app_error(a,API_FAILED);}else{a->doom_running=0;a->doom_starting=0;a->doom_returning=0;screen(a,SCREEN_HOME);}a->next_status=0;break;
    default:break;}free(m);
}
int app_animating(const App *a,uint64_t now){return a->screen==SCREEN_STARTUP||(a->screen==SCREEN_HOME&&a->animate_start&&now-a->animate_start<UI_TRANSITION_MS);}
void app_tick(App *a,uint64_t now){if(artwork_poll(&a->artwork,a->api.generation))a->dirty=1;api_pump(&a->api,now,app_response,a);if(a->awaiting==API_LIBRARIES&&!api_busy(&a->api,API_BROWSE)){a->awaiting=0;app_load(a);}if(a->doom_returning&&a->doom_running&&!api_busy(&a->api,API_CONTROL)&&!api_busy(&a->api,API_OPERATION)){if(!api_doom_stop(&a->api))a->doom_returning=0;}if(a->stop_after_play&&!api_busy(&a->api,API_CONTROL)){a->stop_after_play=0;api_playback_stop(&a->api,a->operation_source);}if(a->notice_until&&now>=a->notice_until){a->notice[0]=0;a->notice_until=0;a->dirty=1;}
    if(a->screen==SCREEN_PLAYER&&a->player_until&&now>=a->player_until&&!a->loading){a->player_until=0;screen(a,a->playback.playing?SCREEN_HIDDEN:SCREEN_HOME);}
    if(a->ready&&!a->frontend_prepared&&!a->doom_running&&a->screen!=SCREEN_DOOM&&a->screen!=SCREEN_HIDDEN&&now>=a->prepare_due&&!api_busy(&a->api,API_CONTROL)){a->prepare_due=UINT64_MAX;if(api_system_prepare(&a->api)){a->prepare_due=now+2000;notice(a,"Preparing remote control.");}}
    if(now>=a->next_status&&!api_busy(&a->api,API_STATUS)){a->next_status=now+1000;if(!a->ready)api_system_ready(&a->api);else if(a->doom_running)api_doom_status(&a->api);else if(a->screen==SCREEN_PAIR&&*a->pair_code){api_auth_poll(&a->api);a->next_status=now+2000;}else api_playback_state(&a->api);}
    if(a->source==SOURCE_JELLYFIN&&(a->screen==SCREEN_BROWSER||a->screen==SCREEN_DETAILS)&&!a->loading&&now>=a->art_due&&!a->artwork.job&&!api_busy(&a->api,API_ARTWORK)){const MediaItem *x=app_selected(a);if(x&&*x->id&&x->id[0]!='@'&&!artwork_find(&a->artwork,x->id)){ui_copy(a->artwork.pending,sizeof(a->artwork.pending),x->id);if(api_artwork_get(&a->api,x->id))a->artwork.pending[0]=0;}}
}
