#include "screens.h"
void render_browser(UiFramebuffer *f,App *a){BrowseNode *n=app_node(a);const ModuleDescriptor *m=app_module(a,a->active_module);render_header(f,m?m->name:"Module",n->title);
    const char *footer=m&&m->search?"SELECT  Open     INFO  Search     BACK  Return":"SELECT  Open     BACK  Return";
    if(a->loading){draw_text(f,UI_SAFE_X,UI_CONTENT_Y+50,"Loading",22,UI_INK,0);render_footer(f,"BACK  Return","");return;}
    if(!a->media.count){draw_text(f,UI_SAFE_X,UI_CONTENT_Y+50,"Nothing here yet",30,UI_INK,0);draw_wrap(f,UI_SAFE_X,UI_CONTENT_Y+102,"Choose another folder or try a search.",18,UI_MUTED,500,3);render_footer(f,footer,"");return;}
    int first=n->selection/6*6;for(int row=0;row<6;row++){int i=first+row;if(i>=a->media.count)break;MediaItem *x=&a->media.item[i];int y=UI_CONTENT_Y+row*UI_ROW_HEIGHT,selected=i==n->selection;if(selected){draw_round(f,UI_LIST_X-8,y-9,UI_LIST_W+16,UI_ROW_HEIGHT-3,5,UI_PANEL,UI_PANEL);ui_fb_rect(f,(UiRect){UI_LIST_X-8,y-5,2,UI_ROW_HEIGHT-11},UI_ACCENT);}draw_text(f,UI_LIST_X+8,y,x->title,18,selected?UI_INK:UI_MUTED,UI_LIST_W-35);if(x->folder)draw_text(f,UI_LIST_X+UI_LIST_W-16,y,"›",18,UI_MUTED,20);}
    const MediaItem *x=app_selected(a);if(x){int y=UI_CONTENT_Y;char key[384];app_art_key(key,sizeof key,a->active_module,x->artwork);if(*x->artwork){artwork_draw(f,artwork_find(&a->artwork,key),UI_DETAIL_X,y);y+=ART_H+18;}else{render_module_icon(f,a,a->active_module,UI_DETAIL_X+(UI_DETAIL_W-78)/2,y+5,78,600);y+=108;}draw_wrap(f,UI_DETAIL_X,y,x->title,22,UI_INK,UI_DETAIL_W,2);y+=56;char meta[128];if(x->year)snprintf(meta,sizeof meta,"%d  ·  %ld min",x->year,x->duration/60);else ui_copy(meta,sizeof meta,*x->subtitle?x->subtitle:x->folder?"Folder":x->playable?"Playable item":"Unavailable");draw_text(f,UI_DETAIL_X,y,meta,14,UI_MUTED,UI_DETAIL_W);}
    char page[64];snprintf(page,sizeof page,"%d / %d%s",a->media.offset+n->selection+1,a->media.total,a->media.has_more?"  +":"");render_footer(f,footer,page);
}
