#include "screens.h"
void render_header(UiFramebuffer *f,const char *title,const char *subtitle){draw_text(f,UI_SAFE_X,UI_HEADER_Y,title,UI_FONT_TITLE,UI_INK,370);draw_text(f,UI_WIDTH-UI_SAFE_X-text_width(subtitle,UI_FONT_BODY),UI_HEADER_Y+11,subtitle,UI_FONT_BODY,UI_MUTED,270);}
void render_footer(UiFramebuffer *f,const char *left,const char *right){draw_text(f,UI_SAFE_X,UI_FOOTER_Y,left,UI_FONT_SMALL,UI_MUTED,470);draw_text(f,UI_WIDTH-UI_SAFE_X-text_width(right,UI_FONT_SMALL),UI_FOOTER_Y,right,UI_FONT_SMALL,UI_MUTED,240);}
void render_button(UiFramebuffer *f,int x,int y,int width,const char *label,int focus){UiColor color=focus?UI_INK:UI_PANEL;draw_round(f,x,y,width,40,7,color,color);draw_center(f,x+width/2,y+9,label,UI_FONT_BODY,focus?COLOR(18,18,22,255):UI_MUTED);}
void render_screen(UiFramebuffer *f,App *a,uint64_t now){
    if(a->screen==SCREEN_HIDDEN||a->screen==SCREEN_NATIVE_APP){ui_fb_clear(f,COLOR(0,0,0,0));return;}draw_background(f,a->screen==SCREEN_HOME&&!a->still?now:0);
    switch(a->screen){case SCREEN_HOME:render_home(f,a,now);break;case SCREEN_BROWSER:render_browser(f,a);break;case SCREEN_KEYBOARD:render_keyboard(f,a);break;case SCREEN_PLAYER:render_player(f,a);break;case SCREEN_SETTINGS:case SCREEN_MODULES:case SCREEN_MODULE_DETAIL:case SCREEN_MODULE_SETTINGS:case SCREEN_ABOUT:render_settings(f,a);break;
    case SCREEN_STARTUP:{render_header(f,"Media center","");draw_center(f,UI_WIDTH/2,178,"Welcome home",36,UI_INK);draw_center(f,UI_WIDTH/2,239,a->message,18,UI_MUTED);draw_round(f,UI_WIDTH/2-80,296,160,3,1,UI_EDGE,UI_EDGE);int pulse=24+(int)((now/20)%112);draw_round(f,UI_WIDTH/2-80,296,pulse,3,1,UI_ACCENT,UI_ACCENT);render_footer(f,"Display  ·  Backend  ·  Remote  ·  Home","BACK  TV");break;}
    case SCREEN_ERROR:render_header(f,"Media center","Let's try that again");draw_text(f,UI_SAFE_X,165,"Something went wrong",30,UI_INK,600);draw_wrap(f,UI_SAFE_X,225,a->message,22,UI_MUTED,600,3);render_button(f,UI_SAFE_X,320,170,"Try again",1);render_footer(f,"SELECT  Try again     INFO  Module settings","BACK  Return");break;
    case SCREEN_PAIR:render_header(f,a->management_pair?"Pair Android management":"Module action","");draw_wrap(f,UI_SAFE_X,145,*a->message?a->message:a->loading?"Working…":"Action complete",22,UI_INK,620,5);if(*a->pair_code)draw_center(f,UI_WIDTH/2,305,a->pair_code,36,UI_ACCENT);render_footer(f,"BACK  Return","");break;
    case SCREEN_DETAILS:{const MediaItem *x=app_selected(a);if(!x)break;const ModuleDescriptor *m=app_module(a,a->active_module);char key[384];app_art_key(key,sizeof key,a->active_module,x->artwork);render_header(f,m?m->name:"Module",x->type);artwork_draw(f,artwork_find(&a->artwork,key),UI_SAFE_X,UI_CONTENT_Y);draw_wrap(f,330,UI_CONTENT_Y,x->title,30,UI_INK,350,2);char meta[96];snprintf(meta,sizeof(meta),"%d  ·  %ld min",x->year,x->duration/60);draw_text(f,330,UI_CONTENT_Y+91,meta,18,UI_MUTED,330);draw_wrap(f,330,UI_CONTENT_Y+126,x->overview,18,UI_MUTED,330,5);render_button(f,UI_SAFE_X,UI_CONTENT_Y+ART_H+24,UI_DETAIL_W,x->resume?"Resume playback":"Play",1);render_footer(f,"SELECT  Watch","BACK  Collection");break;}
    default:break;}
    if(a->notice[0]){draw_round(f,UI_SAFE_X,UI_FOOTER_Y-66,UI_WIDTH-2*UI_SAFE_X,42,5,COLOR(30,30,35,248),COLOR(30,30,35,248));draw_center(f,UI_WIDTH/2,UI_FOOTER_Y-55,a->notice,18,UI_INK);}
    ui_fb_damage(f,(UiRect){0,0,UI_WIDTH,UI_HEIGHT});
}
