#include "screens.h"
static void row(UiFramebuffer *f,int index,int selected,const char *label,const char *value){int first=selected/5*5;if(index<first||index>=first+5)return;int y=UI_CONTENT_Y+12+(index-first)*57,focus=index==selected;if(focus){draw_round(f,UI_SAFE_X-8,y-10,UI_WIDTH-2*UI_SAFE_X+16,48,5,UI_PANEL,UI_PANEL);ui_fb_rect(f,(UiRect){UI_SAFE_X-8,y-5,2,38},UI_ACCENT);}draw_text(f,UI_SAFE_X+9,y,label,20,focus?UI_INK:UI_MUTED,value&&*value?350:620);if(value&&*value)draw_text(f,UI_WIDTH-UI_SAFE_X-245,y+3,value,14,focus?UI_ACCENT:UI_MUTED,240);}
void render_settings(UiFramebuffer *f,App *a){
    if(a->screen==SCREEN_ABOUT){render_header(f,"About ReBox","EARLY ALPHA");draw_wrap(f,UI_SAFE_X,UI_CONTENT_Y+20,"ReBox discovers independently packaged modules. Module software runs on your receiver: install only from sources you trust.",22,UI_INK,620,5);draw_text(f,UI_SAFE_X,UI_CONTENT_Y+220,"Module API 1",18,UI_MUTED,600);render_footer(f,"BACK  Settings","");return;}
    if(a->screen==SCREEN_SETTINGS){render_header(f,"Settings","");row(f,0,a->settings_focus,"Modules","");row(f,1,a->settings_focus,"System / About","");row(f,2,a->settings_focus,"Return home","");}
    else if(a->screen==SCREEN_MODULES){render_header(f,"Modules",a->loading?"Working…":"Installed and bundled");for(int i=0;i<a->modules.count;i++){const ModuleDescriptor *m=&a->modules.items[i];char state[160];snprintf(state,sizeof state,"%s%s%s",m->core?"Core · ":"",!m->installed?"Not installed":!m->enabled?"Disabled":m->healthy?"Enabled":"Error",*m->version?m->version:"");row(f,i,a->settings_focus,m->name,state);}row(f,a->modules.count,a->settings_focus,"Add module from URL","");row(f,a->modules.count+1,a->settings_focus,"Pair Android management","");}
    else if(a->screen==SCREEN_MODULE_DETAIL){const ModuleDescriptor *m=app_module(a,a->managed_module);render_header(f,m?m->name:"Module",m&&m->core?"Core module":"Third-party module");if(m){if(m->installed){row(f,0,a->settings_focus,m->enabled?"Disable":"Enable",m->version);row(f,1,a->settings_focus,"Uninstall (keep data)","");if(m->enabled&&m->healthy&&m->settings)row(f,2,a->settings_focus,"Module settings","");}else row(f,0,a->settings_focus,"Reinstall bundled package","");draw_wrap(f,UI_SAFE_X+9,UI_CONTENT_Y+220,*m->error?m->error:m->description,18,UI_MUTED,620,3);}}
    else{const ModuleDescriptor *m=app_module(a,a->managed_module);render_header(f,m?m->name:"Module","Settings");for(int i=0;i<a->module_settings.field_count;i++){ModuleField *field=&a->module_settings.fields[i];const char *value=field->value;for(int j=0;j<field->choice_count;j++)if(!strcmp(field->value,field->choices[j].value))value=field->choices[j].label;row(f,i,a->settings_focus,field->label,value);}for(int i=0;i<a->module_settings.action_count;i++)row(f,a->module_settings.field_count+i,a->settings_focus,a->module_settings.actions[i].label,"");if(!a->module_settings.field_count&&!a->module_settings.action_count)draw_text(f,UI_SAFE_X,UI_CONTENT_Y+40,"No settings available",22,UI_MUTED,600);}
    render_footer(f,a->loading?"Working…":"SELECT  Open / Save     ← / →  Adjust","BACK  Return");
}
