#include "draw.h"
typedef struct { unsigned cp,offset;int w,h,x,y,advance; } Glyph;
#include "font_data.h"
static unsigned utf8(const char **s){unsigned c=(unsigned char)*(*s)++;if(c<128)return c;int n=c>=240?3:c>=224?2:c>=192?1:0;unsigned cp=c&((1u<<(6-n))-1);if(!n)return '?';for(int i=0;i<n;i++){unsigned v=(unsigned char)**s;if((v&192)!=128)return '?';++*s;cp=cp*64+(v&63);}return cp;}
static int font_index(int size){return size>=36?4:size>=30?3:size>=22?2:size>=18?1:0;}
static const Glyph *glyph(unsigned cp,int index){for(int i=0;i<FONT_GLYPHS;i++)if(font_glyphs[index][i].cp==cp)return &font_glyphs[index][i];return &font_glyphs[index]['?'-32];}
int text_width(const char *s,int size){int n=0,index=font_index(size);while(s&&*s)n+=glyph(utf8(&s),index)->advance;return n;}
void draw_text(UiFramebuffer *f,int x,int y,const char *s,int size,UiColor c,int maxw){int index=font_index(size),origin=x;int clipped=maxw>0&&text_width(s,size)>maxw;const Glyph *e=glyph(0x2026,index);while(s&&*s){const Glyph *g=glyph(utf8(&s),index);if(clipped&&x-origin+g->advance+e->advance>maxw){for(int yy=0;yy<e->h;yy++)for(int xx=0;xx<e->w;xx++){UiColor z=c;z.a=z.a*font_mask[e->offset+yy*e->w+xx]/255;draw_pixel(f,x+e->x+xx,y+e->y+yy,z);}break;}for(int yy=0;yy<g->h;yy++)for(int xx=0;xx<g->w;xx++){UiColor z=c;z.a=z.a*font_mask[g->offset+yy*g->w+xx]/255;draw_pixel(f,x+g->x+xx,y+g->y+yy,z);}x+=g->advance;}}
void draw_center(UiFramebuffer *f,int x,int y,const char *s,int size,UiColor c){draw_text(f,x-text_width(s,size)/2,y,s,size,c,0);}
void draw_wrap(UiFramebuffer *f,int x,int y,const char *s,int size,UiColor c,int width,int lines){char line[512];int n=0;while(*s&&lines>0){const char *end=s;while(*end&&*end!=' ')end++;size_t len=end-s;if(len>240)len=240;if(n&&(n+(int)len+2>500||text_width(line,size)+text_width(" ",size)+text_width(s,size)>width)){/* Fit word only, not remaining paragraph. */char word[256];memcpy(word,s,len);word[len]=0;if(text_width(line,size)+text_width(word,size)+text_width(" ",size)>width){draw_text(f,x,y,line,size,c,width);y+=size+9;lines--;n=0;}}if(n)line[n++]=' ';if(n+(int)len>=511)len=511-n;memcpy(line+n,s,len);n+=len;line[n]=0;s=end;while(*s==' ')s++;}if(n&&lines>0)draw_text(f,x,y,line,size,c,width);}
