#define main hr54_native_main
#include "../hr54_jf.c"
#undef main
#include <assert.h>
static void audio_startup_test(void){
 unsigned char p[9*188],original[sizeof p];memset(p,0xff,sizeof p);
 for(int i=0;i<9;i++){unsigned char *t=p+i*188;t[0]=0x47;t[1]=1;t[2]=2;t[3]=0x10;t[187]=(unsigned char)i;}
 unsigned char *t=p+188;t[1]=0x41;t[2]=0;t[4]=0;unsigned char *m=t+5;m[0]=2;m[1]=0xb0;m[2]=23;m[10]=0xf0;m[11]=0;m[12]=0x1b;m[13]=0xe1;m[14]=2;m[15]=0xf0;m[16]=0;m[17]=0x0f;m[18]=0xe1;m[19]=3;m[20]=0xf0;m[21]=0;
 p[2*188+1]|=64;for(int i=6;i<9;i++){p[i*188+2]=3;p[i*188+3]=(unsigned char)(0x10+i-6);}p[6*188+1]|=64;p[8*188+1]|=64;
 memcpy(original,p,sizeof p);assert(iptv_audio_startup(p,sizeof p)==1);int order[]={0,1,6,7,2,3,4,5,8};for(int i=0;i<9;i++)assert(!memcmp(p+i*188,original+order[i]*188,188));assert(!iptv_audio_startup(p,sizeof p));
 memcpy(p,original,sizeof p);p[6*188+3]|=0x80;memcpy(original,p,sizeof p);assert(!iptv_audio_startup(p,sizeof p));assert(!memcmp(p,original,sizeof p));
 p[6*188+3]&=0x3f;p[8*188+1]&=~64;memcpy(original,p,sizeof p);assert(!iptv_audio_startup(p,sizeof p));assert(!memcmp(p,original,sizeof p));puts("PASS startup audio packet ordering, byte preservation, idempotence, scrambled/incomplete guards");
}
int main(int argc,char **argv){assert(argc==2||argc==3);if(argc==2)audio_startup_test();struct iptv_channel *a=NULL,*b=NULL;size_t n=0,nb=0;assert(!iptv_parse_file(argv[1],&a,&n));if(argc==3){struct sb dump={0};sb_puts(&dump,"[");for(size_t i=0;i<n;i++){if(i)sb_puts(&dump,",");sb_puts(&dump,"{");const char *keys[]={"id","name","tvg-id","tvg-logo","group-title","http-user-agent","http-referrer","url"};const char *vals[]={a[i].id,a[i].name,a[i].tvg,a[i].logo,a[i].group,a[i].ua,a[i].ref,a[i].url};for(int k=0;k<8;k++){if(k)sb_puts(&dump,",");sb_json_str(&dump,keys[k]);sb_puts(&dump,":");sb_json_str(&dump,vals[k]);}sb_puts(&dump,"}");}sb_puts(&dump,"]");puts(dump.p);free(dump.p);for(size_t i=0;i<n;i++)iptv_free_channel(&a[i]);free(a);return 0;}
 assert(n==2096);assert(!iptv_parse_file(argv[1],&b,&nb));assert(n==nb);size_t logos=0,groups=0,ua=0,ref=0,dups=0,queries=0;
 for(size_t i=0;i<n;i++){assert(*a[i].tvg);assert(!strcmp(a[i].id,b[i].id));logos+=!!*a[i].logo;ua+=!!*a[i].ua;ref+=!!*a[i].ref;queries+=!!strchr(a[i].url,'?');int seen=0;for(size_t j=0;j<i;j++){if(!strcmp(a[i].group,a[j].group))seen=1;if(!strcmp(a[i].name,a[j].name)){assert(strcmp(a[i].id,a[j].id));dups++;}}groups+=!seen;}
 assert(groups==26);assert(logos==2075);assert(ua>=63);assert(ref>=30);assert(dups>0);assert(queries>0);printf("Real playlist: %zu entries, %zu groups, %zu logos, %zu UA, %zu Referer, %zu duplicate-name pairs, %zu query URLs\n",n,groups,logos,ua,ref,dups,queries);
 FILE *f=fopen("/tmp/hr54-iptv-edge.m3u","w");assert(f);fputs("#EXTM3U\n#EXTINF:-1 tvg-id=\"id\" tvg-logo=\"logo\" group-title=\"News\" http-user-agent=\"UA, with comma\" http-referrer=\"https://ref/a?q=1,2\",Same, channel\n#EXTVLCOPT:http-user-agent=Explicit, UA\n#EXTVLCOPT:http-referrer=https://override/a?q=2,3\nhttps://host/a.m3u8?token=a%26b&x=1\n#EXTINF:-1 tvg-id=\"id\" group-title=\"News\",Same, channel\nhttps://host/b\n",f);fclose(f);struct iptv_channel *edge;size_t ne;assert(!iptv_parse_file("/tmp/hr54-iptv-edge.m3u",&edge,&ne));assert(ne==2);assert(!strcmp(edge[0].name,"Same, channel"));assert(!strcmp(edge[0].ua,"Explicit, UA"));assert(!strcmp(edge[0].ref,"https://override/a?q=2,3"));assert(!strcmp(edge[0].url,"https://host/a.m3u8?token=a%26b&x=1"));assert(!strcmp(edge[0].logo,"logo"));assert(!*edge[1].ua);assert(strcmp(edge[0].id,edge[1].id));
 char ext[]="tvg-id=\"x\" http-user-agent=\"a,b\",The name, suffix";char *comma=iptv_comma(ext);assert(!strcmp(comma,",The name, suffix"));*comma=0;char *v=iptv_attr(ext,"http-user-agent");assert(!strcmp(v,"a,b"));free(v);
 unsigned char ntp[48]={0},nonce[8]={1,2,3,4,5,6,7,8};time_t epoch;ntp[0]=0x24;ntp[1]=3;memcpy(ntp+24,nonce,8);uint64_t stamp=UINT64_C(1790862347)+UINT64_C(2208988800);for(int j=0;j<4;j++)ntp[40+j]=(unsigned char)(stamp>>(24-j*8));assert(!iptv_ntp_epoch(ntp,48,nonce,&epoch)&&epoch==1790862347);ntp[24]^=1;assert(iptv_ntp_epoch(ntp,48,nonce,&epoch));ntp[24]^=1;ntp[1]=0;assert(iptv_ntp_epoch(ntp,48,nonce,&epoch));
 char out[IPTV_URL_CAP+1];assert(!iptv_resolve(out,sizeof out,"https://host/a/b/master.m3u8?old=1","../seg.ts?token=a%26b"));assert(!strcmp(out,"https://host/a/seg.ts?token=a%26b"));assert(!iptv_resolve(out,sizeof out,"https://host/a/b.m3u8?old=1","?new=2"));assert(!strcmp(out,"https://host/a/b.m3u8?new=2"));assert(!iptv_resolve(out,sizeof out,"https://host/a/b","//cdn/seg.ts?q=1"));assert(!strcmp(out,"https://cdn/seg.ts?q=1"));assert(iptv_resolve(out,sizeof out,"https://host/a/b","file:///etc/passwd"));
 char master[]="#EXTM3U\n#EXT-X-STREAM-INF:BANDWIDTH=26000000,CODECS=\"avc1.640028,mp4a.40.2\"\nbig.m3u8\n#EXT-X-STREAM-INF:BANDWIDTH=4000000,CODECS=\"avc1.640028,mp4a.40.2\"\nok.m3u8?q=1\n#EXT-X-STREAM-INF:BANDWIDTH=6000000,CODECS=\"hvc1.1.6.L120\"\nhevc.m3u8\n";assert(!iptv_variant(master,"https://host/a/master.m3u8",out));assert(!strcmp(out,"https://host/a/ok.m3u8?q=1"));
 char media[]="#EXTM3U\n#EXT-X-MEDIA-SEQUENCE:123\n#EXT-X-TARGETDURATION:4\n#EXTINF:4,\na.ts\n#EXTINF:4,\nb.ts\n#EXT-X-ENDLIST\n";struct iptv_media m;assert(!iptv_media_parse(media,&m));assert(m.count==2&&m.seg[0].seq==123&&m.seg[1].seq==124&&m.end&&m.target==4);iptv_media_free(&m);
 char encrypted[]="#EXTM3U\n#EXT-X-KEY:METHOD=AES-128,URI=\"key\"\n";assert(iptv_media_parse(encrypted,&m));iptv_media_free(&m);char mp4[]="#EXTM3U\n#EXT-X-MAP:URI=\"init.mp4\"\n";assert(iptv_media_parse(mp4,&m));iptv_media_free(&m);
 for(size_t i=0;i<n;i++){iptv_free_channel(&a[i]);iptv_free_channel(&b[i]);}free(a);free(b);for(size_t i=0;i<ne;i++)iptv_free_channel(&edge[i]);free(edge);unlink("/tmp/hr54-iptv-edge.m3u");puts("PASS M3U metadata, explicit options, quoted commas, duplicate IDs, tokens, stable reload, relative HLS, variant policy, sequence, unsupported formats");return 0;}
